<?php

namespace Xgbnl\LaravelRule\Facades;

use Illuminate\Support\Facades\Facade;

class RuleFacade extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return 'laravel-rule'; // TODO: Change the autogenerated stub
    }
}